services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - "./backend/budget.sqlite:/app/backend/budget.sqlite"
    environment:
      - NODE_ENV=development
